#08 Ro'yxat
davlatlar = ['O\'zabekiston', 'AQSH', 'Rossiya', 'XItoy', 'Portugaliya', 'Italiya', 'Angliya', 'Fransiya']
print(davlatlar)
print(len(davlatlar))
print(sorted(davlatlar))
print(sorted(davlatlar, reverse=True))
print(davlatlar)
davlatlar.reverse()
print(davlatlar)
davlatlar.sort()
print(davlatlar)
davlatlar.sort(reverse=True)
print(davlatlar)
juft = list(range(120,1200, 2))
print(juft)
jami = sum(juft)
print(jami)
eng_katta = max(juft)
eng_kichik = min(juft)
print(eng_katta)
print(eng_kichik)
print(juft[:20])
print(juft[18:38])
print(juft[520:])
taomlar = ['osh', 'shashlik', 'kavob', 'gril', 'manti']
nonushta = taomlar[:]
nonushta.remove('osh')
nonushta.remove('shashlik')
nonushta.remove('kavob')
nonushta.remove('gril')
nonushta.remove('manti')
nonushta.append('sut')
nonushta.append('saryog\'')
nonushta = tuple
print(nonushta)
print(taomlar)
